### ISSUE TITLE
Dioxus v0.6.1 support

### ISSUE THREAD

**Issue by Tired-Fox** [RustForWeb/lucide#9]
The 0.6 release of Dioxus has breaking changes for the `Element` return type. This prevents `lucid-dioxus` from being usable with the latest version of Dioxus.

 A bump from the current `0.5.7` to `0.6.1` should fix this for use with the latest versions of Dioxus.

**Comment by DanielleHuisman** [comment]
Fixed by #4.

**Comment by DanielleHuisman** [comment]
Released in [v1.1.0](https://github.com/RustForWeb/lucide/releases/tag/v1.1.0).
